### ISSUE TITLE
possible deprecated argument in plt.show()?

### ISSUE THREAD

**Issue by elleobrien** [wichmann-lab/python-psignifit#54]
Hello, thanks for maintaining this package! I'm a big fan of your work. I'm running the library in Python 3.9 and when I run plot functions like `ps.psigniplot.plotPsych(result)`, I'm getting a matplotlib error (matplotlib version = 3.4.2):

```
ps.psigniplot.plotPsych(result)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv/lib/python3.9/site-packages/psignifit/psigniplot.py", line 139, in plotPsych
    plt.show(0)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 378, in show
    return _backend_mod.show(*args, **kwargs)
TypeError: show() takes 1 positional argument but 2 were given
```

Changing `plt.show(0)` to `plt.show()` in my local copy of `psigniplot.py` fixes the issue. Is this possibly a deprecated form of the function?

**Comment by dekuenstle** [comment]
Yes, you are 100% right, thank you. This is a (deprecated) way to show plots without blocking further computation.
