### ISSUE TITLE
Importing `psignifit` fails for scipy >= 1.12

### ISSUE THREAD

**Issue by pberkes** [wichmann-lab/python-psignifit#74]
The error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pietro.berkes/o/psignifit/psignifit/__init__.py", line 10, in <module>
    from .psignifit import psignifit, getThreshold, getSlope, getSlopePC, biasAna, psignifitFast
  File "/Users/pietro.berkes/o/psignifit/psignifit/psignifit.py", line 14, in <module>
    from . import borders as _b
  File "/Users/pietro.berkes/o/psignifit/psignifit/borders.py", line 13, in <module>
    from .getWeights import getWeights
  File "/Users/pietro.berkes/o/psignifit/psignifit/getWeights.py", line 10, in <module>
    from scipy import diff
ImportError: cannot import name 'diff' from 'scipy' (/Users/pietro.berkes/o/psignifit/venv/lib/python3.9/site-packages/scipy/__init__.py)
```

The imported function comes from NumPy, and since 1.12 SciPy does not import all NumPy functions in its namespace anymore (see https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html#expired-deprecations)

**Comment by pberkes** [comment]
Not relevant, the working branch is `refactor-api`
