### ISSUE TITLE
`import psignifit` fails for matplotlib >= 3.9

### ISSUE THREAD

**Issue by pberkes** [wichmann-lab/python-psignifit#76]
The error is

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pietro.berkes/o/psignifit/psignifit/__init__.py", line 10, in <module>
    from .psignifit import psignifit, getThreshold, getSlope, getSlopePC, biasAna, psignifitFast
  File "/Users/pietro.berkes/o/psignifit/psignifit/psignifit.py", line 27, in <module>
    from . import psigniplot as plot
  File "/Users/pietro.berkes/o/psignifit/psignifit/psigniplot.py", line 539, in <module>
    colorMap = getColorMap(), 
  File "/Users/pietro.berkes/o/psignifit/psignifit/psigniplot.py", line 334, in getColorMap
    _cm.register_cmap(name = 'Tuebingen', cmap = MAP)
AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'
```

The problem is that the `register_cmap` function has been deprecated in 3.7.0 and removed in 3.9.0:

https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#removals

**Comment by pberkes** [comment]
Not relevant, the working branch is refactor-api
